CONFIG -= qt
CONFIG += console

QMAKE_CXXFLAGS = -std=c++11
QMAKE_CXXFLAGS_DEBUG =
QMAKE_CXXFLAGS_RELEASE = -O2  -flto
QMAKE_CXXFLAGS_WARN_ON =
QMAKE_CXXFLAGS_APP =
QMAKE_LFLAGS = -rdynamic
QMAKE_LFLAGS_DEBUG =
QMAKE_LFLAGS_RELEASE = -O1 -flto
QMAKE_LFLAGS_RPATH =

INCLUDEPATH += ../common
SOURCES += *.cpp ../common/*.cpp
HEADERS += ../common/*.h
